config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
     post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users 
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Slugable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true, length: {minimum: 3}

  slugable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  

  validates :body, presence: true, length: {minimum: 1}
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Slugable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  slugable_column :title
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Slugable

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 5}

  slugable_column :username

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to root_path
    end
  end

  
  #def require_admin
   #access_denied unless logged_in? && current_user.admin?
  #end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_user, only: [:new, :create]
  #before_action :require_admin, only: [:new, :create]

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category was successfully created!"
      redirect_to posts_path
    else
      render :new
    end
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by slug: params[:id]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
    
  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was successfully added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on a comment once."
        end
        redirect_to :back
      end
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  #before_action :require_admin, only: [:edit]

  def index
    @posts = Post.all.sort_by {|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was successfully edited."
      redirect_to posts_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on a post once."
        end
        redirect_to :back
      end
      format.js
    end

  end

private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've loged in!"
      redirect_to root_path
    else
      flash[:error] = "There is soemthing wrong with your username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]


  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Account as been created, you are now logged in."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

private
   
  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You're not allowed to do that."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(url)
    url.starts_with?('http://') ? url : "http://#{url}"
  end

  def display_datetime(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end
      dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>
 &nbsp

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "Create New Category" %>

<%= render 'shared/errors', obj: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
  <%= f.submit "Create Category", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Post', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class='row' id='color_box'>
  <% if logged_in? %>
    <div class='span0 well text-center'>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      </br>
      <span id='comment_<%= comment.id %>_votes'><%= comment.total_votes %> votes</span>
      </br>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>
  <% else %>
    <div class='span0 well text-center'>
      <%= comment.total_votes %> votes
    </div>
  <% end %>
  <div class='well span8'>
      <em>"<%= comment.body %>"</em>

      <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>

    </br>
      <span class='quiet'>by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
      <small>at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
  alert("You can only vote once.");
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
   Categories <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
    <% Category.all.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
    <% if logged_in? %> 
      <li class='divider'></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class='icon-plus'></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class="nav_item">
    <%= link_to "New Post", new_post_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class='btn-group nav_item'>
    <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
          <i class='icon-circle-arrow-left'></i>
          logout
        <% end %>
      </li>

    </ul>
  </div>
  
<% else %>
  <div class="nav_item">
  <%= link_to "Log in", login_path, class: 'btn btn-small' %>
  </div>
  <div class="nav_item">
  <%= link_to "Register", new_user_path, class: 'btn btn-small btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brent Palmer - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? "Create Post": "Update Post", class: "btn btn-primary") %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id='color_box' classs='row'>
  <% if logged_in? %>
    <div class='span1 well text-center'>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      </br>
      <span id='post_<%= post.slug %>_votes'><%= post.total_votes %> votes</span>
      </br>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>
  <% else %>
    <div class='span1 well text-center'>
     <%= post.total_votes %> votes
    </div>
  <% end %>
  <div class='span9 well'>
  <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) unless post.creator.blank? %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit this post" %>

<% if current_user %>
<%= render 'form' %>
<% end %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
<%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f|%>
  <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
      <%= f.label :body, "Leave a comment:" %>
      <%= f.text_area :body, rows: 3, class: 'span4'%>
    </div>
    <%= f.submit "Create Comment", class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
  alert('You can only vote on a post once.');
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='well'>
  <%= form_for @user do |f|%>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
    </div>
    <%= f.submit (@user.new_record? ? 'Register' : "Update Profile"), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render "shared/content_title", title: "Register" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
  </dl>
</div>

<h5><%= @user.username %>'s Activity</h5>

<ul class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% elsif params[:tab] == 'comments' %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, show_post: true %>
  <% end %>
<% end %>